// This file is automatically generated by `smolarch gen-c`. Do not edit!

#ifndef SMOL_EXTRACT_S
#error "SMOL_EXTRACT_S must be defined"
#endif
#ifndef SMOL_EXTRACT_Z
#error "SMOL_EXTRACT_Z must be defined"
#endif

#define SMOL_FIELD_EXTRACT_RS(inst) ( \
    (SMOL_EXTRACT_Z(inst, 0, 5) << 0) \
)

#define SMOL_FIELD_EXTRACT_RD(inst) ( \
    (SMOL_EXTRACT_Z(inst, 5, 5) << 0) \
)

#define SMOL_FIELD_EXTRACT_SHAMT3(inst) ( \
    (SMOL_EXTRACT_Z(inst, 7, 3) << 0) \
)

#define SMOL_FIELD_EXTRACT_SHAMT7(inst) ( \
    (SMOL_EXTRACT_Z(inst, 4, 1) << 6) | \
    (SMOL_EXTRACT_Z(inst, 5, 2) << 4) | \
    (SMOL_EXTRACT_Z(inst, 0, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_IMM5(inst) ( \
    (SMOL_EXTRACT_S(inst, 0, 5) << 0) \
)

#define SMOL_FIELD_EXTRACT_IMM7(inst) ( \
    (SMOL_EXTRACT_S(inst, 4, 1) << 6) | \
    (SMOL_EXTRACT_Z(inst, 5, 2) << 4) | \
    (SMOL_EXTRACT_Z(inst, 0, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_IMM10(inst) ( \
    (SMOL_EXTRACT_S(inst, 4, 1) << 9) | \
    (SMOL_EXTRACT_Z(inst, 5, 5) << 4) | \
    (SMOL_EXTRACT_Z(inst, 0, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_UIMM10(inst) ( \
    (SMOL_EXTRACT_Z(inst, 4, 1) << 9) | \
    (SMOL_EXTRACT_Z(inst, 5, 5) << 4) | \
    (SMOL_EXTRACT_Z(inst, 0, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_UIMM11(inst) ( \
    (SMOL_EXTRACT_Z(inst, 4, 1) << 10) | \
    (SMOL_EXTRACT_Z(inst, 5, 6) << 4) | \
    (SMOL_EXTRACT_Z(inst, 0, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_UIMM15(inst) ( \
    (SMOL_EXTRACT_Z(inst, 4, 1) << 14) | \
    (SMOL_EXTRACT_Z(inst, 5, 10) << 4) | \
    (SMOL_EXTRACT_Z(inst, 0, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_TABLE(inst) ( \
    (SMOL_EXTRACT_Z(inst, 7, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_RT(inst) ( \
    (SMOL_EXTRACT_Z(inst, 16, 5) << 0) \
)

#define SMOL_FIELD_EXTRACT_SKIP(inst) ( \
    (SMOL_EXTRACT_Z(inst, 5, 5) << 0) \
)

#define SMOL_FIELD_EXTRACT_IMM10L(inst) ( \
    (SMOL_EXTRACT_S(inst, 20, 1) << 9) | \
    (SMOL_EXTRACT_Z(inst, 21, 5) << 4) | \
    (SMOL_EXTRACT_Z(inst, 16, 4) << 0) \
)

#define SMOL_FIELD_EXTRACT_IMM10S(inst) ( \
    (SMOL_EXTRACT_S(inst, 9, 1) << 9) | \
    (SMOL_EXTRACT_Z(inst, 21, 5) << 4) | \
    (SMOL_EXTRACT_Z(inst, 5, 4) << 0) \
)
