// This file is automatically generated by `smolarch gen-c`. Do not edit!

#define SMOL_INST_INFO_CLASS(info) (info)[0]
#define SMOL_INST_INFO_OPCODE_LEN(info) (info)[1]
#define SMOL_INST_INFO_NAME_LEN(info) (info)[2]
#define SMOL_INST_INFO_OPERANDS_COUNT(info) (info)[3]
#define SMOL_INST_INFO_FLAGS(info) (info)[4]
#define SMOL_INST_INFO_OPCODE_PTR(info) (&(info)[5])
#define SMOL_INST_INFO_NAME_PTR(info) (SMOL_INST_INFO_OPCODE_PTR(info) + SMOL_INST_INFO_OPCODE_LEN(info))
#define SMOL_INST_INFO_NAME(info) ((const char *) SMOL_INST_INFO_NAME_PTR(info))
#define SMOL_INST_INFO_OPERANDS_PTR(info) (SMOL_INST_INFO_NAME_PTR(info) + SMOL_INST_INFO_NAME_LEN(info))
#define SMOL_INST_INFO_LEN(info) \
  ((int) (SMOL_INST_INFO_OPERANDS_PTR(info) + SMOL_INST_INFO_OPERANDS_COUNT(info) * 2 - info))
