// This file is automatically generated by `smolarch gen-c`. Do not edit!

#ifndef SMOL_DEFINE_CLASS
#error "SMOL_DEFINE_CLASS must be defined"
#endif

SMOL_DEFINE_CLASS(NONE, "none", head)
SMOL_DEFINE_CLASS(COND, "cond", body_cond)
SMOL_DEFINE_CLASS(INT, "int", body_int)
SMOL_DEFINE_CLASS(LOAD, "load", body_load)
SMOL_DEFINE_CLASS(LI, "li", body_li)
