// This file is automatically generated by `smolarch gen-c`. Do not edit!

#ifdef SMOL_DEFINE_CLASS
SMOL_DEFINE_CLASS(NONE, "none", head)
SMOL_DEFINE_CLASS(COND, "cond", body_cond)
SMOL_DEFINE_CLASS(INT, "int", body_int)
SMOL_DEFINE_CLASS(LOAD, "load", body_load)
SMOL_DEFINE_CLASS(LI, "li", body_li)
#endif

#ifdef SMOL_DEFINE_CLASS_CHILD
SMOL_DEFINE_CLASS_CHILD(INT, COND)
SMOL_DEFINE_CLASS_CHILD(LOAD, COND)
SMOL_DEFINE_CLASS_CHILD(LOAD, INT)
#endif
