// This file is automatically generated by `smolarch gen-c`. Do not edit!

#ifndef SMOL_DEFINE_OPERAND
#error "SMOL_DEFINE_OPERAND must be defined"
#endif

SMOL_DEFINE_OPERAND(IMM, "IMM")
SMOL_DEFINE_OPERAND(REG_X_DST, "REG_X_DST")
SMOL_DEFINE_OPERAND(REG_X_SRC, "REG_X_SRC")
SMOL_DEFINE_OPERAND(SKIP_TARGET, "SKIP_TARGET")
