// This file is automatically generated by `smolarch gen-c`. Do not edit!

#ifndef SMOL_DEFINE_OPERAND
#error "SMOL_DEFINE_OPERAND must be defined"
#endif

SMOL_DEFINE_OPERAND(IMM, "IMM")
SMOL_DEFINE_OPERAND(REG_X, "REG_X")
